# Generated by Django 6.0.7 on 2026-09-09 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'plantilla de mapeo de importación',
                'verbose_name_plural': 'plantillas de mapeo de importación',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='orders/imports/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pendiente de mapeo'), ('mapping', 'Mapeado, pendiente de confirmar'), ('processing', 'Procesando'), ('done', 'Terminado'), ('failed', 'Falló')], default='pending', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'importación de pedidos',
                'verbose_name_plural': 'importaciones de pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='address',
            name='recipient_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('web', 'Autoservicio (web)'), ('manual', 'Carga manual'), ('import', 'Importación de archivo'), ('api', 'API de ingesta'), ('webhook', 'Webhook entrante')], default='web', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('user', 'external_id'), name='unique_order_external_id_per_user'),
        ),
        migrations.AddField(
            model_name='importmapping',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_mappings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderimport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_imports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='importmapping',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_import_mapping_name_per_user'),
        ),
    ]
