# Generated by Django 6.0.7 on 2026-09-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_unique_order_external_id_per_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='origin',
            field=models.CharField(choices=[('own', 'Agenda del usuario'), ('shipment', 'Dirección de un envío')], default='own', max_length=20),
        ),
    ]
