# Generated by Django 6.0.7 on 2026-09-02 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_email', models.CharField(blank=True, default='', max_length=254)),
                ('category', models.CharField(choices=[('auth', 'Autenticación'), ('users', 'Usuarios'), ('roles', 'Roles'), ('orders', 'Pedidos'), ('support', 'Soporte')], max_length=20)),
                ('action', models.CharField(choices=[('auth.login_success', 'Login exitoso'), ('auth.login_failed', 'Login fallido'), ('auth.lockout', 'Bloqueo de cuenta'), ('auth.logout', 'Logout'), ('auth.password_change', 'Cambio de contraseña'), ('auth.password_reset', 'Restablecimiento de contraseña'), ('user.create', 'Usuario creado'), ('user.update', 'Usuario actualizado'), ('user.deactivate', 'Usuario desactivado'), ('user.reactivate', 'Usuario reactivado'), ('user.unlock', 'Usuario desbloqueado'), ('user.role_change', 'Cambio de rol de usuario'), ('role.create', 'Rol creado'), ('role.update', 'Rol actualizado'), ('role.delete', 'Rol eliminado'), ('role.permissions_update', 'Permisos de rol actualizados'), ('order.create', 'Pedido creado'), ('order.status_change', 'Cambio de estado de pedido'), ('order.cancel', 'Pedido cancelado'), ('support.create', 'Mensaje de soporte creado'), ('support.status_change', 'Cambio de estado de soporte'), ('support.reply', 'Respuesta de soporte')], max_length=40)),
                ('target_type', models.CharField(blank=True, default='', max_length=50)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('target_repr', models.CharField(blank=True, default='', max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de auditoría',
                'verbose_name_plural': 'registros de auditoría',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='audit_audit_created_6e540c_idx'), models.Index(fields=['category'], name='audit_audit_categor_b5df0b_idx'), models.Index(fields=['actor'], name='audit_audit_actor_i_17b775_idx')],
            },
        ),
    ]
