# Generated by Django 6.0.7 on 2026-09-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_action_alter_auditlog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('auth.login_success', 'Login exitoso'), ('auth.login_failed', 'Login fallido'), ('auth.lockout', 'Bloqueo de cuenta'), ('auth.logout', 'Logout'), ('auth.password_change', 'Cambio de contraseña'), ('auth.password_reset', 'Restablecimiento de contraseña'), ('user.create', 'Usuario creado'), ('user.update', 'Usuario actualizado'), ('user.deactivate', 'Usuario desactivado'), ('user.reactivate', 'Usuario reactivado'), ('user.unlock', 'Usuario desbloqueado'), ('user.role_change', 'Cambio de rol de usuario'), ('role.create', 'Rol creado'), ('role.update', 'Rol actualizado'), ('role.delete', 'Rol eliminado'), ('role.permissions_update', 'Permisos de rol actualizados'), ('order.create', 'Pedido creado'), ('order.status_change', 'Cambio de estado de pedido'), ('order.cancel', 'Pedido cancelado'), ('order.import', 'Importación de pedidos'), ('order.webhook_ingest', 'Pedido recibido por webhook'), ('support.create', 'Mensaje de soporte creado'), ('support.status_change', 'Cambio de estado de soporte'), ('support.reply', 'Respuesta de soporte'), ('label.create', 'Rótulo creado'), ('label.update', 'Rótulo actualizado'), ('label.delete', 'Rótulo eliminado'), ('label.render', 'Rótulo renderizado (PDF)'), ('label.batch', 'Rótulos generados por lote'), ('template.create', 'Plantilla de rótulo creada'), ('template.update', 'Plantilla de rótulo actualizada'), ('template.delete', 'Plantilla de rótulo eliminada'), ('plantilla.create', 'Plantilla estructurada creada'), ('plantilla.update', 'Plantilla estructurada actualizada'), ('plantilla.delete', 'Plantilla estructurada eliminada'), ('variable_rotulo.create', 'Variable de rótulo creada'), ('variable_rotulo.update', 'Variable de rótulo actualizada'), ('variable_rotulo.delete', 'Variable de rótulo eliminada'), ('document.delete', 'Documento eliminado'), ('documento.create', 'Documento fuente subido'), ('documento.delete', 'Documento fuente eliminado'), ('importacion_rotulo.create', 'Importación de rótulo lanzada'), ('integration_key.create', 'Clave de integración creada'), ('integration_key.delete', 'Clave de integración eliminada'), ('incoming_webhook.create', 'Webhook entrante creado'), ('webhook_endpoint.create', 'Webhook saliente creado')], max_length=40),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='category',
            field=models.CharField(choices=[('auth', 'Autenticación'), ('users', 'Usuarios'), ('roles', 'Roles'), ('orders', 'Pedidos'), ('support', 'Soporte'), ('labels', 'Rótulos'), ('documents', 'Documentos'), ('integrations', 'Integraciones'), ('processing', 'Procesamiento')], max_length=20),
        ),
    ]
