# Generated by Django 6.0.7 on 2026-09-10 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_documento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionRotulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completada', 'Completada'), ('error', 'Error')], default='pendiente', max_length=20, verbose_name='estado')),
                ('modelo', models.CharField(blank=True, default='', max_length=60, verbose_name='modelo')),
                ('propuesta', models.JSONField(blank=True, null=True, verbose_name='propuesta')),
                ('respuesta_cruda', models.JSONField(blank=True, null=True, verbose_name='respuesta cruda')),
                ('error', models.TextField(blank=True, default='', verbose_name='error')),
                ('tokens_entrada', models.PositiveIntegerField(default=0, verbose_name='tokens de entrada')),
                ('tokens_salida', models.PositiveIntegerField(default=0, verbose_name='tokens de salida')),
                ('request_id', models.CharField(blank=True, default='', max_length=100, verbose_name='request id')),
                ('creada_en', models.DateTimeField(auto_now_add=True, verbose_name='creada en')),
                ('finalizada_en', models.DateTimeField(blank=True, null=True, verbose_name='finalizada en')),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importaciones_rotulo', to=settings.AUTH_USER_MODEL, verbose_name='creada por')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importaciones', to='documents.documento', verbose_name='documento')),
            ],
            options={
                'verbose_name': 'importación de rótulo',
                'verbose_name_plural': 'importaciones de rótulo',
                'ordering': ['-creada_en'],
            },
        ),
    ]
