# Generated by Django 6.0.7 on 2026-09-21 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_rename_documento_uploadedlabelfile'),
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importacionrotulo',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importaciones', to='documents.uploadedlabelfile', verbose_name='documento'),
        ),
    ]
