# Generated by Django 6.0.7 on 2026-08-19 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_seed_roles'),
        ('accounts', '0002_create_role_groups'),
    ]

    operations = [
    ]
