# Generated by Django 6.0.7 on 2026-08-20 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_0001_seed_roles_0002_create_role_groups'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'permiso de rol',
                'verbose_name_plural': 'permisos de rol',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='GroupRolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permission_links', to='auth.group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_links', to='accounts.rolepermission')),
            ],
            options={
                'verbose_name': 'asignación de permiso a rol',
                'verbose_name_plural': 'asignaciones de permiso a rol',
                'constraints': [models.UniqueConstraint(fields=('group', 'permission'), name='uniq_group_role_permission')],
            },
        ),
    ]
