# Generated by Django 6.0.7 on 2026-09-02 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_seed_support_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_support_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='response',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En curso'), ('resolved', 'Resuelto')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
