# Generated by Django 6.0.7 on 2026-10-08 16:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_address_origin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(choices=[('andreani', 'Andreani')], max_length=30)),
                ('environment', models.CharField(choices=[('production', 'Producción'), ('qa', 'Pruebas (QA)')], default='production', max_length=20)),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('password_encrypted', models.TextField(blank=True, default='')),
                ('client_code', models.CharField(blank=True, default='', max_length=50)),
                ('contracts', models.JSONField(blank=True, default=list)),
                ('sender_name', models.CharField(blank=True, default='', max_length=150)),
                ('sender_email', models.EmailField(blank=True, default='', max_length=254)),
                ('sender_phone', models.CharField(blank=True, default='', max_length=30)),
                ('sender_document', models.CharField(blank=True, default='', max_length=20)),
                ('origin_street', models.CharField(blank=True, default='', max_length=120)),
                ('origin_number', models.CharField(blank=True, default='', max_length=20)),
                ('origin_floor', models.CharField(blank=True, default='', max_length=20)),
                ('origin_apartment', models.CharField(blank=True, default='', max_length=20)),
                ('origin_postal_code', models.CharField(blank=True, default='', max_length=10)),
                ('origin_city', models.CharField(blank=True, default='', max_length=120)),
                ('default_weight_kg', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=8)),
                ('default_volume_cm3', models.PositiveIntegerField(default=4000)),
                ('token_encrypted', models.TextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrier_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cuenta de transportista',
                'verbose_name_plural': 'cuentas de transportista',
            },
        ),
        migrations.CreateModel(
            name='CarrierShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(choices=[('andreani', 'Andreani')], max_length=30)),
                ('contract', models.CharField(max_length=50)),
                ('delivery_kind', models.CharField(choices=[('home', 'A domicilio'), ('branch', 'En sucursal o punto HOP')], default='home', max_length=20)),
                ('branch_id', models.CharField(blank=True, default='', max_length=30)),
                ('branch_name', models.CharField(blank=True, default='', max_length=150)),
                ('tracking_number', models.CharField(max_length=50)),
                ('group_number', models.CharField(blank=True, default='', max_length=50)),
                ('package_count', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Creado, falta entregarlo al correo'), ('in_transit', 'En camino'), ('at_branch', 'Esperando retiro en sucursal'), ('delivered', 'Entregado'), ('issue', 'Con problema'), ('returning', 'En devolución'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('carrier_status', models.CharField(blank=True, default='', max_length=120)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='carriers.carrieraccount')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carrier_shipments', to='orders.order')),
            ],
            options={
                'verbose_name': 'envío',
                'verbose_name_plural': 'envíos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarrierShipmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField()),
                ('cycle', models.CharField(blank=True, default='', max_length=50)),
                ('event', models.CharField(blank=True, default='', max_length=80)),
                ('reason', models.CharField(blank=True, default='', max_length=150)),
                ('sub_reason', models.CharField(blank=True, default='', max_length=150)),
                ('status_text', models.CharField(blank=True, default='', max_length=150)),
                ('branch', models.CharField(blank=True, default='', max_length=150)),
                ('comment', models.CharField(blank=True, default='', max_length=500)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='carriers.carriershipment')),
            ],
            options={
                'verbose_name': 'movimiento de envío',
                'verbose_name_plural': 'movimientos de envío',
                'ordering': ['occurred_at', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='carrieraccount',
            constraint=models.UniqueConstraint(fields=('owner', 'carrier'), name='unique_carrier_account_per_owner'),
        ),
        migrations.AddIndex(
            model_name='carriershipment',
            index=models.Index(fields=['status', 'last_checked_at'], name='carriers_ca_status_3128ef_idx'),
        ),
        migrations.AddConstraint(
            model_name='carriershipment',
            constraint=models.UniqueConstraint(fields=('carrier', 'tracking_number'), name='unique_carrier_tracking_number'),
        ),
        migrations.AddConstraint(
            model_name='carriershipmentevent',
            constraint=models.UniqueConstraint(fields=('shipment', 'occurred_at', 'event'), name='unique_shipment_event'),
        ),
    ]
