# Generated by Django 5.2.8 on 2026-08-19 16:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='descripción')),
                ('ancho_mm', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='ancho (mm)')),
                ('alto_mm', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='alto (mm)')),
                ('dpi', models.PositiveIntegerField(default=300, validators=[django.core.validators.MinValueValidator(1)], verbose_name='DPI')),
                ('orientacion', models.CharField(choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal')], default='vertical', max_length=10, verbose_name='orientación')),
                ('metadatos', models.JSONField(blank=True, default=dict, verbose_name='metadatos')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
                ('creada_en', models.DateTimeField(auto_now_add=True, verbose_name='creada en')),
                ('actualizada_en', models.DateTimeField(auto_now=True, verbose_name='actualizada en')),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='creada por')),
            ],
            options={
                'verbose_name': 'plantilla',
                'verbose_name_plural': 'plantillas',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='VariableRotulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Identificador interno en minúsculas, p. ej. numero_bulto.', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9_]*$', 'El código debe empezar con una letra minúscula y contener solo minúsculas, números y guiones bajos (por ejemplo: numero_bulto).')], verbose_name='código')),
                ('etiqueta', models.CharField(help_text='Nombre legible que se muestra en la interfaz.', max_length=100, verbose_name='etiqueta')),
                ('descripcion', models.TextField(blank=True, default='', help_text='Qué representa este campo dentro del rótulo.', verbose_name='descripción')),
                ('tipo_dato', models.CharField(choices=[('texto', 'Texto'), ('qr', 'Código QR'), ('codigo_barras', 'Código de barras'), ('imagen', 'Imagen')], default='texto', max_length=20, verbose_name='tipo de dato')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
                ('es_sistema', models.BooleanField(default=False, help_text='Las variables del sistema no se pueden eliminar.', verbose_name='del sistema')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('creada_en', models.DateTimeField(auto_now_add=True, verbose_name='creada en')),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variables_creadas', to=settings.AUTH_USER_MODEL, verbose_name='creada por')),
            ],
            options={
                'verbose_name': 'variable de rótulo',
                'verbose_name_plural': 'variables de rótulo',
                'ordering': ['orden', 'etiqueta'],
            },
        ),
        migrations.CreateModel(
            name='ElementoPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('variable', 'Variable'), ('texto_estatico', 'Texto estático'), ('linea', 'Línea'), ('recuadro', 'Recuadro')], default='variable', max_length=20, verbose_name='tipo')),
                ('contenido', models.TextField(blank=True, default='', verbose_name='contenido')),
                ('x_mm', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='x (mm)')),
                ('y_mm', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='y (mm)')),
                ('ancho_mm', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='ancho (mm)')),
                ('alto_mm', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='alto (mm)')),
                ('estilo', models.JSONField(blank=True, default=dict, verbose_name='estilo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos', to='labels.plantilla', verbose_name='plantilla')),
                ('variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='elementos', to='labels.variablerotulo', verbose_name='variable')),
            ],
            options={
                'verbose_name': 'elemento de plantilla',
                'verbose_name_plural': 'elementos de plantilla',
                'ordering': ['orden', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('contenido', ''), ('tipo', 'variable'), ('variable__isnull', False)), models.Q(('tipo', 'texto_estatico'), ('variable__isnull', True), models.Q(('contenido', ''), _negated=True)), models.Q(('contenido', ''), ('tipo__in', ['linea', 'recuadro']), ('variable__isnull', True)), _connector='OR'), name='labels_elemento_coherente_con_tipo')],
            },
        ),
    ]
