# Generated by Django 6.0.7 on 2026-09-10 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0003_seed_default_label_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='default', max_length=50)),
                ('prefix', models.CharField(blank=True, max_length=20)),
                ('padding', models.PositiveSmallIntegerField(default=6)),
                ('current', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'secuencia de rótulos',
                'verbose_name_plural': 'secuencias de rótulos',
                'unique_together': {('owner', 'key')},
            },
        ),
    ]
