# Generated by Django 6.0.7 on 2026-09-09 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('prefix', models.CharField(db_index=True, max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'clave de integración',
                'verbose_name_plural': 'claves de integración',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncomingWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('secret', models.CharField(max_length=64)),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_webhooks', to=settings.AUTH_USER_MODEL)),
                ('integration_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_webhooks', to='integrations.integrationkey')),
            ],
            options={
                'verbose_name': 'webhook entrante',
                'verbose_name_plural': 'webhooks entrantes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('url', models.URLField()),
                ('secret', models.CharField(max_length=64)),
                ('events', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'webhook saliente',
                'verbose_name_plural': 'webhooks salientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=50)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('response_body', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='integrations.webhookendpoint')),
            ],
            options={
                'verbose_name': 'entrega de webhook',
                'verbose_name_plural': 'entregas de webhook',
                'ordering': ['-created_at'],
            },
        ),
    ]
