# Generated by Django 6.0.7 on 2026-09-14 16:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('tiendanube', 'Tiendanube')], max_length=30)),
                ('external_store_id', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('store_url', models.URLField(blank=True, default='')),
                ('access_token_encrypted', models.TextField(blank=True, default='')),
                ('scopes', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('active', 'Conectada'), ('revoked', 'Desconectada'), ('error', 'Con errores')], default='active', max_length=20)),
                ('last_error', models.TextField(blank=True, default='')),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('connected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tienda conectada',
                'verbose_name_plural': 'tiendas conectadas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('tiendanube', 'Tiendanube')], max_length=30)),
                ('event_type', models.CharField(max_length=80)),
                ('resource_id', models.CharField(blank=True, default='', max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('done', 'Procesado'), ('failed', 'Falló')], default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_error', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='integrations.storeconnection')),
            ],
            options={
                'verbose_name': 'evento de integración',
                'verbose_name_plural': 'eventos de integración',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='storeconnection',
            constraint=models.UniqueConstraint(fields=('platform', 'external_store_id'), name='unique_store_per_platform'),
        ),
        migrations.AddIndex(
            model_name='integrationevent',
            index=models.Index(fields=['status', 'next_attempt_at'], name='integ_event_due_idx'),
        ),
    ]
