# Generated by Django 6.0.7 on 2026-09-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_integrationevent_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconnection',
            name='sender_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='storeconnection',
            name='sender_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='storeconnection',
            name='sender_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
