# Generated by Django 6.0.7 on 2026-09-22 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_storeconnection_sender_address_and_more'),
        ('labels', '0010_default_template_sender_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconnection',
            name='default_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='labels.labeltemplate'),
        ),
        migrations.AddField(
            model_name='storeconnection',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='store_logos/%Y/%m/'),
        ),
    ]
