# Generated by Django 6.0.7 on 2026-09-22 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_storeconnection_default_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreLabelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_label_id', models.CharField(max_length=64)),
                ('external_fulfillment_order_id', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('ready', 'Generado'), ('failed', 'Falló'), ('canceled', 'Cancelado')], default='pending', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('file', models.FileField(blank=True, null=True, upload_to='store_labels/%Y/%m/')),
                ('download_token', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_requests', to='integrations.storeconnection')),
            ],
            options={
                'verbose_name': 'rótulo pedido por la tienda',
                'verbose_name_plural': 'rótulos pedidos por la tienda',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('connection', 'external_label_id'), name='unique_store_label_request')],
            },
        ),
    ]
