# Generated by Django 6.0.7 on 2026-09-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_storelabelrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storelabelrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('ready', 'Generado'), ('failed', 'Falló'), ('canceled', 'Cancelado'), ('suspended', 'Suspendido')], default='pending', max_length=20),
        ),
    ]
