# Generated by Django 6.0.7 on 2026-09-23 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_alter_storelabelrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_code', models.CharField(default='standard', max_length=40)),
                ('option_name', models.CharField(default='Envío estándar', max_length=100)),
                ('postal_code_from', models.CharField(max_length=8)),
                ('postal_code_to', models.CharField(max_length=8)),
                ('weight_up_to_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='ARS', max_length=3)),
                ('delivery_days_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('delivery_days_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_rates', to='integrations.storeconnection')),
            ],
            options={
                'verbose_name': 'tarifa de envío',
                'verbose_name_plural': 'tarifas de envío',
                'ordering': ['connection', 'option_code', 'postal_code_from', 'weight_up_to_kg'],
                'indexes': [models.Index(fields=['connection', 'option_code', 'is_active'], name='integration_connect_8d4ffd_idx')],
            },
        ),
    ]
