# Generated by Django 6.0.7 on 2026-09-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_shippingrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconnection',
            name='label_printer_dpmm',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(6, '152 dpi'), (8, '203 dpi (la mayoría)'), (12, '300 dpi'), (24, '600 dpi')], null=True),
        ),
    ]
