# Generated by Django 6.0.7 on 2026-09-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0010_storeconnection_label_printer_dpmm'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconnection',
            name='refresh_token_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='storeconnection',
            name='refresh_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeconnection',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='integrationevent',
            name='platform',
            field=models.CharField(choices=[('tiendanube', 'Tiendanube'), ('shopify', 'Shopify')], max_length=30),
        ),
        migrations.AlterField(
            model_name='storeconnection',
            name='external_store_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='storeconnection',
            name='platform',
            field=models.CharField(choices=[('tiendanube', 'Tiendanube'), ('shopify', 'Shopify')], max_length=30),
        ),
    ]
