# Generated by Django 6.0.7 on 2026-10-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0011_shopify_and_expiring_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconnection',
            name='webhook_secret_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='integrationevent',
            name='platform',
            field=models.CharField(choices=[('tiendanube', 'Tiendanube'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce')], max_length=30),
        ),
        migrations.AlterField(
            model_name='storeconnection',
            name='platform',
            field=models.CharField(choices=[('tiendanube', 'Tiendanube'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce')], max_length=30),
        ),
    ]
