# Generated by Django 6.0.7 on 2026-10-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0012_woocommerce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationevent',
            name='platform',
            field=models.CharField(choices=[('tiendanube', 'Tiendanube'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('vtex', 'VTEX')], max_length=30),
        ),
        migrations.AlterField(
            model_name='storeconnection',
            name='platform',
            field=models.CharField(choices=[('tiendanube', 'Tiendanube'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('vtex', 'VTEX')], max_length=30),
        ),
    ]
