# Generated by Django 5.2.8 on 2026-08-25 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='rotulos/%Y/%m/', verbose_name='archivo')),
                ('nombre_original', models.CharField(help_text='Nombre que tenía el archivo en la máquina del usuario.', max_length=255, verbose_name='nombre original')),
                ('tipo_mime', models.CharField(choices=[('image/jpeg', 'image/jpeg'), ('image/png', 'image/png'), ('image/gif', 'image/gif'), ('image/webp', 'image/webp'), ('application/pdf', 'application/pdf')], max_length=50, verbose_name='tipo MIME')),
                ('tamano_bytes', models.PositiveIntegerField(verbose_name='tamaño (bytes)')),
                ('subido_en', models.DateTimeField(auto_now_add=True, verbose_name='subido en')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to=settings.AUTH_USER_MODEL, verbose_name='subido por')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ['-subido_en'],
            },
        ),
    ]
